---
apiVersion: v1
kind: Namespace
metadata:
  name: spark

---
# Service HEADLESS per discovery (usato da StatefulSet e driver)
apiVersion: v1
kind: Service
metadata:
  name: spark-master-hs
  namespace: spark
spec:
  clusterIP: None
  selector:
    app: spark
    role: master
  ports:
    - name: rpc
      port: 7077
      targetPort: 7077
    - name: ui
      port: 8080
      targetPort: 8080

---
# UI del master esposta via NodePort (solo per browser)
apiVersion: v1
kind: Service
metadata:
  name: spark-master-ui
  namespace: spark
spec:
  type: NodePort
  selector:
    app: spark
    role: master
  ports:
    - name: ui
      port: 8080
      targetPort: 8080
      nodePort: 30085

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spark-worker
  namespace: spark
spec:
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: worker
          image: docker.io/library/spark:3.5.1
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash","-lc"]
          args:
            - |
              /opt/spark/sbin/start-worker.sh spark://spark-master-hs.spark.svc.cluster.local:7077 && \
              tail -f /opt/spark/logs/*worker*.out
          ports:
            - name: ui
              containerPort: 8081
          env:
            - name: SPARK_NO_DAEMONIZE
              value: "true"
            - name: SPARK_WORKER_CORES
              value: "4"        
            - name: SPARK_WORKER_MEMORY
              value: "6g"       
          resources:
            requests:
              cpu: "2"
              memory: "3Gi"
            limits:
              cpu: "4"
              memory: "6Gi"